### ISSUE TITLE
Brain dump

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/babw#6]
My thoughts are scattered and I want to get them written down. Here seems like an OK place to do that. Feel free to edit this, comment, or move this text somewhere else.

# Background

Christian created a bunch of avatars in Blender last year. Not only that, he built them in a way that allows them to be mixed-and-matched. Let's create a web application that allows anyone to create an avatar with the pieces that Christian made.

# Open Questions
- [Do we build a standalone application or start with a fork of Hubs / Spoke? ](https://github.com/mozilla/babw/issues/3)
- [What's the scope of the project?](https://github.com/mozilla/babw/issues/2)

## What core technologies do we want to use?

- [Javascript or Typescript?](https://github.com/mozilla/babw/issues/4)

- [Should we also build a backend application?](https://github.com/mozilla/babw/issues/5)

**Comment by Abhijay007** [comment]
Is it something like the apple AI emoji? 

It seems like an interesting project I read a bit about it in #2  and  #3 and found it quite scalable. If we are able to provide a blender-like avatar by just enrolling face on the front cam and also able to provide a customization option, then it will be a very good idea to start with. 

Means it takes hours to build a simple character that looks like you in a blender and this application can do that in minutes by just enrolling your face. 

I don't know I am understanding this project correctly or not, but I found it quite interesting.

(With the ref #5) And yeah, this project may also need a back-end because as user wants to store his/her designs, projects or get back to work from where he/she left customization, then we need to implement a user dashboard for the same.

**Comment by johnshaughnessy** [comment]
> If we are able to provide a blender-like avatar by just enrolling face on the front cam and also able to provide a customization option, then it will be a very good idea to start with.

That sounds cool (but probably out of scope).

> Is it something like the apple AI emoji?

No, the goals for this project are less ambitious than that :sweat_smile: .

> this project may also need a back-end because as user wants to store his/her designs, projects or get back to work from where he/she left customization, then we need to implement a user dashboard for the same

That could certainly be a stretch goal. It's unclear if we'll get that far or go in that direction. (The intention of this project is to spend one week building something fun / useful / explorative.)
